name: fns_traders
description: FNS TRADERS Quality Medicines
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.7
  pdf: ^3.11.0
  printing: ^5.11.1
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.5
flutter:
  uses-material-design: true
  assets:
    - fns_logo.png
