name: fns_traders
description: FNS Traders
publish_to: 'none'
version: 1.0.0+1
environment:
  sdk: '>=3.0.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  intl: ^0.19.0
  pdf: ^3.10.7
  printing: ^5.11.1
  print_bluetooth_thermal: 1.2.1
  esc_pos_utils: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/

dependency_overrides:
  image: ^4.0.17
