name: fns_traders_customer
description: FNS Traders Customer App
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: any
  cloud_firestore: any
  firebase_auth: any
  pdf: ^3.10.7
  printing: ^5.11.0
  print_bluetooth_thermal: ^1.0.0+2
  esc_pos_utils_plus: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
