name: Build FNS TRADER'S APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.35.0'
          channel: stable

      - name: Create Android files
        run: |
          flutter create --platforms=android temp_app
          cp -r temp_app/android .
          rm -rf temp_app
      - name: Set NDK version
        run: |
          sed -i 's/27.0.12077973/27.3.13750724/g' android/app/build.gradle.kts

      - name: Put FNS app code in lib
        run: |
          mkdir -p lib
          cp main.dart lib/main.dart

      - name: Get dependencies
        run: flutter pub get

      - name: Build APK
        run: flutter build apk --release --target=main.dart

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: FNS-TRADERS-APK
          path: build/app/outputs/flutter-apk/app-release.apk
