name: Build Admin APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: 'stable'
      - name: Fix Android
        run: |
          rm -rf android
          flutter create --project-name fns_trader --platforms=android .
          flutter pub get
      - name: Build Admin APK
        run: flutter build apk -t lib/main.dart
      - uses: actions/upload-artifact@v4
        with:
          name: Admin-APK
          path: build/app/outputs/flutter-apk/app-release.apk
