name: Build Customer APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
      - run: flutter pub get
      - run: flutter build apk --target-platform android-arm,android-arm64 --split-per-apk -t lib/main_customer.dart
      - uses: actions/upload-artifact@v3
        with:
          name: customer-apk
          path: build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk
